name: Build wheels

# Only build on tagged releases
on:
  push:
    branches:
      - '*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      # symlinks the compiler paths automatically for us
      - name: Install GNU Fortran
        uses: modflowpy/install-gfortran-action@v1

      # Only on the Windows runner
      - name: Add Windows environment settings
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "FFLAGS=-O1" >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.10'

      - name: Download source files
        run: |
          python .github/workflows/download_mirror.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"
          # Skip 32 bit windows builds due to compiler
          CIBW_SKIP: "*-win32"
          CIBW_BEFORE_BUILD: "echo $PATH && env && echo $GITHUB_PATH && which gcc && which gfortran"
          # TODO: Look into universal2 support, but compilers and options
          #       will be tricky with the Fortran code and tests...
          CIBW_ARCHS_MACOS: arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Download source files
        run: |
          python .github/workflows/download_mirror.py

      - name: Build sdist
        run: |
          python -m pip install meson-python meson ninja build
          python -m build --sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
