name: Build wheels

# Only build on tagged releases
on:
  push:
    branches:
      - '*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      # Only on the Windows runner
      - name: Add Windows environment settings
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "F77=gfortran" >> $GITHUB_ENV
          echo "F90=gfortran" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Brew installs
        run: |
          brew install gfortran
          gfortran --version

      - name: Download source files
        run: |
          python .github/workflows/download_mirror.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_BUILD: "cp39-*"
          # TODO: Look into universal2 support, but compilers and options
          #       will be tricky with the Fortran code and tests...
          CIBW_ARCHS_MACOS: universal2

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
