name: Build wheels

# Only build on tagged releases
on:
  push:
    branches:
      - '*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      FC: gfortran-9
      F77: gfortran-9
      F90: gfortran-9
      CC: gcc-9
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      # Only on the Windows runner
      - name: Add Windows environment settings
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "F77=gfortran" >> $GITHUB_ENV
          echo "F90=gfortran" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Download source files
        run: |
          python .github/workflows/download_mirror.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"
          # TODO: Look into universal2 support, but compilers and options
          #       will be tricky with the Fortran code and tests...
          CIBW_ARCHS_MACOS: x86_64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.9'

      - name: Download source files
        run: |
          python .github/workflows/download_mirror.py

      - name: Build sdist
        run: |
          python -m pip install meson-python meson ninja build
          python -m build --sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
